const lotData = [
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Vintage Clock",
    description: "A beautiful vintage clock from the 19th century.",
    category: "Antiques",
    price: "$250",
    date: "2024-05-21",
    image: "",
    username: "johnDoe",
  },
  {
    name: "Modern Art Painting",
    description: "A stunning piece of modern art.",
    category: "Art",
    price: "$1500",
    date: "2024-05-20",
    image: "",
    username: "janeDoe",
  },
  {
    name: "Luxury Watch",
    description: "A luxury watch with diamond studs.",
    category: "Watches",
    price: "$5000",
    date: "2024-05-19",
    image: "",
    username: "johnDoe",
  },
];

export default lotData;
